### ISSUE TITLE
Resolve dependabot alerts 

### ISSUE THREAD

**Issue by nickgarfield** [faktorfi/faktor#4]
Introduced 23h ago with the React code.

<img width="1258" alt="Screen Shot 2021-12-18 at 14 11 58" src="https://user-images.githubusercontent.com/8634334/146654433-d6838b03-fdec-408c-9230-8381ec6ac352.png">

**Comment by rasreee** [comment]
is this issue not resolved? i don't see the alerts on my end

**Comment by nickgarfield** [comment]
Looks like we resolved these through updating a dependency.
