### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by nickgarfield** [faktorfi/faktor#4]
Right now, we're using Tailwind's default font choices. Let's add some branded fonts to frontend app. In particular, we use **TT Firs Neue** for headers and **FK Grotesk Neue** for body fonts. Contact @nickgarfield for the font files.

![Typography](https://user-images.githubusercontent.com/8634334/141756492-c2a848d2-c528-4b59-b0a3-1e613a6639f1.png)

**Comment by Eliascm17** [comment]
Whoever takes care of this issue be sure to contact @nickgarfield for font files.
